/** 플랫폼 공통 에러 코드 — 서비스 간 로깅·클라이언트 분기용. */
export const PlatformErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_OTP: "INVALID_OTP",
  OTP_REQUIRED: "OTP_REQUIRED",
  OTP_EXPIRED: "OTP_EXPIRED",
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_ORDER: "INVALID_ORDER",
  ORDER_NOT_CANCELLABLE: "ORDER_NOT_CANCELLABLE",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  DUPLICATE_APPROVAL: "DUPLICATE_APPROVAL",
  RATE_LIMITED: "RATE_LIMITED"
} as const;

export type PlatformErrorCode = (typeof PlatformErrorCodes)[keyof typeof PlatformErrorCodes];
